<a href="https://colab.research.google.com/github/kanitha09/Projects_ML/blob/main/Housepriceprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
import math

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
import statsmodels.api as sm

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.preprocessing import RobustScaler

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
import sklearn.metrics as metrics

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [ ]:
raw_data = pd.read_csv("/content/data.csv")

In [ ]:
raw_data.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [ ]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

In [ ]:
raw_data.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
date,4600,70,2014-06-23 00:00:00,142,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,4600.0,NaN,NaN,NaN,551962.988473,563834.702547,0.0,322875.0,460943.461539,654962.5,26590000.0
bedrooms,4600.0,NaN,NaN,NaN,3.40087,0.908848,0.0,3.0,3.0,4.0,9.0
bathrooms,4600.0,NaN,NaN,NaN,2.160815,0.783781,0.0,1.75,2.25,2.5,8.0
sqft_living,4600.0,NaN,NaN,NaN,2139.346957,963.206916,370.0,1460.0,1980.0,2620.0,13540.0
sqft_lot,4600.0,NaN,NaN,NaN,14852.516087,35884.436145,638.0,5000.75,7683.0,11001.25,1074218.0
floors,4600.0,NaN,NaN,NaN,1.512065,0.538288,1.0,1.0,1.5,2.0,3.5
waterfront,4600.0,NaN,NaN,NaN,0.007174,0.084404,0.0,0.0,0.0,0.0,1.0
view,4600.0,NaN,NaN,NaN,0.240652,0.778405,0.0,0.0,0.0,0.0,4.0
condition,4600.0,NaN,NaN,NaN,3.451739,0.67723,1.0,3.0,3.0,4.0,5.0
sqft_above,4600.0,NaN,NaN,NaN,1827.265435,862.168977,370.0,1190.0,1590.0,2300.0,9410.0
sqft_basement,4600.0,NaN,NaN,NaN,312.081522,464.137228,0.0,0.0,0.0,610.0,4820.0
yr_built,4600.0,NaN,NaN,NaN,1970.786304,29.731848,1900.0,1951.0,1976.0,1997.0,2014.0
yr_renovated,4600.0,NaN,NaN,NaN,808.608261,979.414536,0.0,0.0,0.0,1999.0,2014.0
street,4600,4525,2520 Mulberry Walk NE,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,4600,44,Seattle,1573,NaN,NaN,NaN,NaN,NaN,NaN,NaN
statezip,4600,77,WA 98103,148,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,4600,1,USA,4600,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
x1 = raw_data.drop(['price', 'date', 'street', 'city', 'statezip', 'country'], axis = 1)
y = raw_data['price']

In [ ]:
x = sm.add_constant(x1)

In [ ]:
results = sm.OLS(y,x).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.218
Model:                            OLS   Adj. R-squared:                  0.216
Method:                 Least Squares   F-statistic:                     116.1
Date:                Thu, 23 Nov 2023   Prob (F-statistic):          5.03e-235
Time:                        14:27:05   Log-Likelihood:                -66877.
No. Observations:                4600   AIC:                         1.338e+05
Df Residuals:                    4588   BIC:                         1.339e+05
Df Model:                          11
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const          4.584e+06   6.85e+05      6.689      0.000    3.24e+06    5.93e+06
bedrooms      -5.804e+04   1.05e+04     -5.531      0.000   -7.86e+04   -3.75e+04
bathrooms       5.72e+04    1.7e+04      3.363      0.001    2.39e+04    9.05e+04
sqft_living     164.4116      9.779     16.813      0.000     145.241     183.582
sqft_lot         -0.6912      0.213     -3.250      0.001      -1.108      -0.274
floors         3.981e+04   1.87e+04      2.129      0.033    3143.011    7.65e+04
waterfront     3.553e+05   9.38e+04      3.789      0.000    1.71e+05    5.39e+05
view            4.57e+04    1.1e+04      4.167      0.000    2.42e+04    6.72e+04
condition      3.184e+04    1.3e+04      2.441      0.015    6269.622    5.74e+04
sqft_above       97.0378      9.714      9.989      0.000      77.993     116.082
sqft_basement    67.3738     13.661      4.932      0.000      40.591      94.157
yr_built      -2378.2101    341.615     -6.962      0.000   -3047.939   -1708.481
yr_renovated      6.5727      8.634      0.761      0.447     -10.355      23.500
==============================================================================
Omnibus:                    12845.801   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        601962895.545
Skew:                          35.530   Prob(JB):                         0.00
Kurtosis:                    1773.770   Cond. No.                     1.07e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.12e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""